export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";

export const FETCH_SIGNUP_REQUEST = "FETCH_SIGNUP_REQUEST";
export const FETCH_SIGNUP_SUCCESS = "FETCH_SIGNUP_SUCCESS";
export const FETCH_SIGNUP_FAILURE = "FETCH_SIGNUP_FAILURE";

export const SET_IS_LOGIN = "SET_IS_LOGIN";
export const FETCH_LOGOUT = "FETCH_LOGOUT";

export const FETCH_ADMIN_LOGIN_SUCCESS = "FETCH_ADMIN_LOGIN_SUCCESS";
export const FETCH_ADMIN_LOGIN_FAILURE = "FETCH_ADMIN_LOGIN_FAILURE";
export const FETCH_ADMIN_LOGOUT = "FETCH_ADMIN_LOGOUT";