export const FETCH_TOURNAMENT_LIST_SUCCESS = "FETCH_TOURNAMENT_LIST_SUCCESS";
export const FETCH_TOURNAMENT_LIST_FAILURE = "FETCH_TOURNAMENT_LIST_FAILURE";

export const FETCH_REGISTER_TO_TOURNAMENT_SUCCESS = "FETCH_REGISTER_TO_TOURNAMENT_SUCCESS";
export const FETCH_REGISTER_TO_TOURNAMENT_FAILURE = "FETCH_REGISTER_TO_TOURNAMENT_FAILURE";

export const FETCH_GET_UNFILLED_TEAM_LIST_SUCCESS = "FETCH_GET_UNFILLED_TEAM_LIST_SUCCESS";
export const FETCH_GET_UNFILLED_TEAM_LIST_FAILURE = "FETCH_GET_UNFILLED_TEAM_LIST_FAILURE";
