export const FETCH_GET_BEST_PLAYER_SUCCESS = "FETCH_GET_BEST_PLAYER_SUCCESS";
export const FETCH_GET_BEST_PLAYER_FAILURE = "FETCH_GET_BEST_PLAYER_FAILURE";

export const FETCH_GET_PLAYER_SUCCESS = "FETCH_GET_PLAYER_SUCCESS";
export const FETCH_GET_PLAYER_FAILURE = "FETCH_GET_PLAYER_FAILURE";
