export const FETCH_GET_BEST_TEAM_SUCCESS = "FETCH_GET_BEST_TEAM_SUCCESS";
export const FETCH_GET_BEST_TEAM_FAILURE = "FETCH_GET_BEST_TEAM_FAILURE";

export const FETCH_GET_TEAM_SUCCESS = "FETCH_GET_TEAM_SUCCESS";
export const FETCH_GET_TEAM_FAILURE = "FETCH_GET_TEAM_FAILURE";

export const FETCH_GET_FOUND_TEAM_SUCCESS = "FETCH_GET_FOUND_TEAM_SUCCESS";
export const FETCH_GET_FOUND_TEAM_FAILURE = "FETCH_GET_FOUND_TEAM_FAILURE";

export const FETCH_REGISTER_TO_TEAM_SUCCESS = "FETCH_REGISTER_TO_TEAM_SUCCESS";
export const FETCH_REGISTER_TO_TEAM_FAILURE = "FETCH_REGISTER_TO_TEAM_FAILURE"

export const FETCH_CREATE_TEAM_SUCCESS = "FETCH_CREATE_TEAM_SUCCESS";
export const FETCH_CREATE_TEAM_FAILURE = "FETCH_CREATE_TEAM_FAILURE";