export const FETCH_SWEEPSTAKE_LIST_SUCCESS = "FETCH_SWEEPSTAKE_LIST_SUCCESS";
export const FETCH_SWEEPSTAKE_LIST_FAILURE = "FETCH_SWEEPSTAKE_LIST_FAILURE";

export const FETCH_SWEEPSTAKE_REGISTER_SUCCESS = "FETCH_SWEEPSTAKE_REGISTER_SUCCESS";
export const FETCH_SWEEPSTAKE_REGISTER_FAILURE = "FETCH_SWEEPSTAKE_REGISTER_FAILURE";
