export const FETCH_GET_USER_INFO_SUCCESS = "FETCH_GET_USER_INFO_SUCCESS";
export const FETCH_GET_USER_INFO_FAILURE = "FETCH_GET_USER_INFO_FAILURE";

export const FETCH_UPDATE_USER_SUCCESS = "FETCH_UPDATE_USER_SUCCESS";
export const FETCH_UPDATE_USER_FAILURE = "FETCH_UPDATE_USER_FAILURE";

export const FETCH_CHANGE_PASSWORD_SUCCESS = "FETCH_CHANGE_PASSWORD_SUCCESS";
export const FETCH_CHANGE_PASSWORD_FAILURE = "FETCH_CHANGE_PASSWORD_FAILURE";

